### ISSUE TITLE
WooCommerce: Discount codes can be used by other customers

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/affiliatewp-store-credit#15]
Once a coupon code has been generated for store credit, it is possible for the customer to share that code with a different customer instead of redeeming it. This wouldn't be much of a problem except that when the code is used by the other customer, the amount of credit on the original customer's account is not reduced.

**Comment by pippinsplugins** [comment]
Reported here https://secure.helpscout.net/conversation/152210102/23893/?folderId=205530

**Comment by sumobi** [comment]
:+1:

**Comment by michaelbeil** [comment]
:100:

**Comment by ryanduff** [comment]
Well crap. 

I'd actually argue that the expected behavior is to only allow coupon usage by who it was generated for. Coupons are generated on the fly at checkout if someone wants to use it. Further, a the coupon is only valid for a single use, and expires after 2 days. 

While technically, you can generate a coupon at checkout, and share it, this is not an intended behavior.

I think what's needed here is an extra meta key with the user id in `generate_coupon()` and a check of that value against the user id in `process_used_coupon()`

**Comment by pippinsplugins** [comment]
@ryanduff I agree
