### ISSUE TITLE
Pay certain affiliates in store credit only

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-store-credit#3]
We could add a checkbox on the edit affiliate screen to enable store credit only for specific affiliates.

As per the comments below there could be an option in the global settings which would allow auto-created affiliates to receive store credit, but manually registered affiliates (ones that fill out the registration form) to receive standard cash payouts. And of course, these can easily be overridden on a per-affiliate basis, but might help in the automation of things.

**Comment by wordmaid** [comment]
Another request for per-affiliate store credit option here: https://secure.helpscout.net/conversation/177516040/29184/

**Comment by ramiabraham** [comment]
https://secure.helpscout.net/conversation/208415991/35163/?folderId=297160

**Comment by ramiabraham** [comment]
This could be created with consideration for https://github.com/AffiliateWP/affiliatewp-store-credit/issues/17, or as one single method, with both admin and affiliate dashboard views.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/247859120/41649/?folderId=205524

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/247859120/41649/?folderId=205524

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/247859120/41649/?folderId=205524

**Comment by gspice** [comment]
Another:
https://secure.helpscout.net/conversation/313986857/52280/?folderId=205529

**Comment by DrewAPicture** [comment]
Another request: https://secure.helpscout.net/conversation/368311430/59654/?folderId=205529

**Comment by DrewAPicture** [comment]
I'd probably also look at a global filter on top of the ability to opt certain affiliates out via a setting.

Relatedish: #33, #35

**Comment by gspice** [comment]
Another one 👍 
https://secure.helpscout.net/conversation/368311430/59654/?folderId=205529

**Comment by ramiabraham** [comment]
@DrewAPicture Definitely agree that a filter/filters is the way to go here.

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/379951185/60900/?folderId=205529

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/385403367/61564/?folderId=205529

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/400066644/63351/?folderId=205529

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/402522682/63608/?folderId=205529

**Comment by gspice** [comment]
Add another
https://secure.helpscout.net/conversation/554809658/79766/?folderId=205529

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/557870477/80041/?folderId=205529

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/585925340/82672/?folderId=205529

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/593097101/83403?folderId=634609

**Comment by pippinsplugins** [comment]
@tubiz could you please put this on your todo list for right after Lifetime Commissions?

**Comment by gspice** [comment]
Another:
https://secure.helpscout.net/conversation/605210692/84573/?folderId=205529

**Comment by tubiz** [comment]
A global option has been added to allow all affiliates to receive store credit.

![store credit global enable](https://user-images.githubusercontent.com/602184/43214954-c43ab8be-9032-11e8-86da-ac022267f4fa.png)

Likewise, an option has been added to enable it per affiliate if the global option is not enabled.

![store credit affiliate enable](https://user-images.githubusercontent.com/602184/43215016-e7e2dfa8-9032-11e8-81f9-50fa04ccf8e6.png)

Payout method column

![store credit affiliate screen](https://user-images.githubusercontent.com/602184/43215468-1e9273a0-9034-11e8-8fde-2552f2b47278.png)

> As per the comments below there could be an option in the global settings which would allow auto-created affiliates to receive store credit, but manually registered affiliates (ones that fill out the registration form) to receive standard cash payouts.

Is it still necessary to add this, because if the global option is enabled this will take precedence over what is set above?

**Comment by michaelbeil** [comment]
I can see a global option has been added:
![screen shot on 2018-07-25 at 19_40_19](https://user-images.githubusercontent.com/4752949/43217842-0038cbb6-9043-11e8-9997-bbb344ce8849.png)

And there is a per affiliate option to enable store credit if the global is not enabled:
 
![screen shot on 2018-07-25 at 19_44_22](https://user-images.githubusercontent.com/4752949/43217899-323dbe8c-9043-11e8-8019-442aa98dcc91.png)

>As per the comments below there could be an option in the global settings which would allow auto-created affiliates to receive store credit, but manually registered affiliates (ones that fill out the registration form) to receive standard cash payouts.

I don't think it is necessary to add this, since if the global option is enabled, it will enable store credit for **all** affiliates.

**Comment by pippinsplugins** [comment]
Excellent!

@gspice could you test this as well?

**Comment by gspice** [comment]
This is very exciting! 

A few things:
* Can we default it so **Enable For All Affiliates** is checked by default since this is the way it behaves now?  Then existing users can go through and make changes as they go.

* First tested existing functionality - WooCommerce integration:
   1. Checked the box to **Enable For All Affiliates**
   2. Went to _Affiliates > Referrals_ and checked two referrals for the same affiliate, at the top clicked on _Bulk Actions > Mark As Paid_, then **Apply** button.
   3.  Received warning at the top of the screen:
```
Warning: A non-numeric value encountered in /app/public/wp-content/plugins/affiliatewp-store-credit-issue-3/integrations/class-woocommerce.php on line 43

**Comment by tubiz** [comment]
> Can we default it so Enable For All Affiliates is checked by default since this is the way it behaves now? Then existing users can go through and make changes as they go.

@gspice I am not sure this is possible. The warning has been fixed in PHP 7.1

**Comment by pippinsplugins** [comment]
We could add an upgrade routine to set the option to enabled during the
update.

**Comment by tubiz** [comment]
Okay. I will add that.

**Comment by tubiz** [comment]
An upgrade routine has been added to set Enable For All Affiliates? to enabled if Store Credit is enabled.

**Comment by michaelbeil** [comment]
@tubiz is there a way that I could easily test the upgrade routine?

**Comment by tubiz** [comment]
@michaelbeil yes, make sure only the `Enable Store Credit` checkbox is checked, then set the version number to `2.3` here https://github.com/AffiliateWP/affiliatewp-store-credit/blob/7cb8432de59dd50f76bd4ad09a1c48bfa0683e6a/affiliatewp-store-credit.php#L74

You can then refresh the settings page.

**Comment by michaelbeil** [comment]
Okay. 

It looks like this works well.

**Comment by gspice** [comment]
Re-tested everything I could think of with Woo, everything looking good.   Will give it a go with EDD next.
