### ISSUE TITLE
It would be great if there is Withdrawal button

### ISSUE THREAD

**Issue by alexlii1971** [AffiliateWP/affiliatewp-store-credit#98]
Hello,

It would be great if there is a withdrawal button at affiliate frontend dashboard so that they could apply for transfer commission to store credit.

Alternatively,  it even much better for administrator to set automatically payout as store points, but not manually "mark" at backend.

Thanks

**Comment by michaelbeil** [comment]
We are looking to possibly add such a feature in this issue over here: https://github.com/AffiliateWP/affiliatewp-store-credit/issues/85. 

Automatically _setting a referral as paid / set store credit to paid_ is in this feature request here: https://github.com/AffiliateWP/affiliatewp-store-credit/issues/1.

Therefore, I am going to close this issue, since these features are already covered.
